package fr.gervais.rest.app.models;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity(name = "Profile")
public class Profile {
	
	//Attributes.
	@Id
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
			)
	private final UUID id = null;	//This value will be auto-generated by the repository interface.

	private String login;
	private String password;
	private String name;
	private String mail;
	private String phone;
	
	@JsonIgnore
    @ManyToMany(mappedBy = "profileReservations")
    private Set<Reservation> reservations = new HashSet<>();

	//Constructors.
	
	public Profile() {
		
	}

	public Profile(String login, String password, String name, String mail, String phone) {
		super();
		this.login = login;
		this.password = password;
		this.name = name;
		this.mail = mail;
		this.phone = phone;
	}

	//Get'er & Set'er Methods.
	
	public UUID getid() {
		return this.id;
	}

	public String getlogin() {
		return this.login;
	}

	public String getpassword() {
		return this.password;
	}
	
	public String getname() {
		return this.name;
	}

	public String getmail() {
		return this.mail;
	}

	public String getphone() {
		return this.phone;
	}
	
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setlogin(String login) {
		this.login = login;
	}

	public void setpassword(String password) {
		this.password = password;
	}
	
	public void setname(String name) {
		this.name = name;
	}

	public void setmail(String mail) {
		this.mail = mail;
	}

	public void setphone(String phone) {
		this.phone = phone;
	}
	
	//Custom Methods.
	
}
