package fr.gervais.rest.app.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class User {
	
	//Attributes.
	@Id
	@GeneratedValue
	private int id;	//This value will be auto-generated by the repository interface.

	private String name;
	private String login;
	private String password;
	private String mail;
	private String phone;

	//Constructors.
	
	public User() {
		
	}

	public User(String name, String login, String password, String mail, String phone) {
		super();
		this.name = name;
		this.login = login;
		this.password = password;
		this.mail = mail;
		this.phone = phone;
	}
	
	public User(int id, String name, String login, String password, String mail, String phone) {
		super();
		this.id = id;
		this.name = name;
		this.login = login;
		this.password = password;
		this.mail = mail;
		this.phone = phone;
	}

	//Get'er & Set'er Methods.
	
	public int getid() {
		return this.id;
	}

	public String getname() {
		return this.name;
	}

	public String getlogin() {
		return this.login;
	}

	public String getpassword() {
		return this.password;
	}

	public String getmail() {
		return this.mail;
	}

	public String getphone() {
		return this.phone;
	}

	public void setid(int id) {
		this.id = id;
	}

	public void setname(String name) {
		this.name = name;
	}

	public void setlogin(String login) {
		this.login = login;
	}

	public void setpassword(String password) {
		this.password = password;
	}

	public void setmail(String mail) {
		this.mail = mail;
	}

	public void setphone(String phone) {
		this.phone = phone;
	}
	
	//Custom Methods.
	
}
